### PR TITLE
Work with modern gnupg

### PR DESCRIPTION
**Pull request by dkg**
This pull request contains several patches that make GnuPG::Interface work with modern GnuPG (version 2.1 or later).

https://rt.cpan.org/Public/Bug/Display.html?id=102651

The main sticking point is that it's not clear to me how to ensure that `--pinentry-mode loopback` only gets passed to modern versions of GnuPG (and not to the "classic" version).  See my posting on https://lists.gnupg.org/pipermail/gnupg-devel/2016-October/031800.html for more detail.

### CODE REVIEW

**Comment by dkg** [comment]
What's the word on this?

**Comment by dkg** [comment]
I've updated this pull request to follow GnuPG upstream's best practices for test-suites related to GnuPG: using a temporary homedir, and terminating the gpg-agent when necessary.

**Comment by mschout** [comment]
I vote that the detection of when to use --pinentry-mode=loopback or not is done by parsing the gnupg version output.  This could be computed on demand and cached if necessary to avoid forking to check the version every single time.  Sure, there is a potential race condition where the machine upgraded to gnupg 2.1+ between the time version() was called and the time a gnupg command happened, but thats going to be a very rare occurrance, and a restart of whatever service is affected would fix that.   Upgrading gnupg from classic to modern introduces all kinds of changes so I'd expect this kind of breakage frankly.  Given that RHEL/CentOS 7 shipped with gnupg 2.0, were going to see v2.0.x for quite some time.

Given that GnuPG is now up to version 2.2.x, it seems unlikely that the problem will get fixed upstream.

**Comment by ntyni** [comment]
Hi,  7c85ac40660861e7507c43d043323c3f1b83921b and b356e7fda15e39e037da1888a24000a96fc85c90 provide further test suite amendments for GnuPG 2.2.6 and 2.2.8 compatibility that we intend to use in Debian on top of @dkg 's work discussed here (which we've been using for quite a while now).

Hope they are useful to somebody else too.

**Comment by intrigeri** [comment]
Hi, it looks like a rebased version of this branch was merged into master. Is there anything left to do before this PR (and, I suppose, https://rt.cpan.org/Public/Bug/Display.html?id=102651) can be closed?

**Comment by cbrandtbuffalo** [comment]
As noted previously, work from this branch has been merged in slightly different forms and a new version of GnuPG::Interface has been released. Thanks to everyone who contributed updates!

**Pull request closed without merging**
